name: meropalika
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.10.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_advanced_drawer: ^1.3.5
  get: ^4.6.5
  google_fonts: ^4.0.4
  image_picker: ^0.8.7+4
  dio: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - res/
